services:
  aurorajs:
    build: .
    image: aurorajs
    container_name: aurorajs
    restart: unless-stopped
    pull_policy: never
    env_file: .env
    volumes:
      - "aurorajs-data:${DATA_PATH:-/var/aurorajs/data}"

volumes:
  aurorajs-data:
