services:
  aurorajs:
    build: .
    image: aurorajs
    container_name: aurorajs
    restart: unless-stopped
    pull_policy: never
    environment:
      DATABASE_PATH: /var/aurorajs/data/db.sqlite3
    env_file: .env
    volumes:
      - "${DATA_PATH:-aurorajs-data}:/var/aurorajs/data"

volumes:
  aurorajs-data:
