name: PR Has Type

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: PR has exactly one type label
        run: |
          types=0

          echo "${{contains(github.event.pull_request.labels.*.name, 't-patch')}}"
          if [[ "${{contains(github.event.pull_request.labels.*.name, 't-patch')}}" == "true" ]];
          then
            echo "no"
            types=$((types+1))
          fi

          if [[ "${{contains(github.event.pull_request.labels.*.name, 't-minor')}}" == "true" ]];
          then
            types=$((types+1))
          fi

          if [[ "${{contains(github.event.pull_request.labels.*.name, 't-major')}}" == "true" ]];
          then
            types=$((types+1))
          fi

          if [[ $types != 1 ]];
          then
            echo $types
            echo "PR needs to have exactly one type label" && exit 1
          fi
