name: Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "migrations/**"
      - "docker-compose.yml"
      - "Dockerfile"
      - "scripts/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      APP_DIR: ${{ secrets.APP_DIR }}
      DATA_PATH: ${{ secrets.DATA_PATH }}
      GUILD_ID: ${{ secrets.GUILD_ID }}
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Deploy into production
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: APP_DIR,DATA_PATH,GUILD_ID,TOKEN
          script: |
            cd $(mktemp -d)
            git clone https://github.com/${{ github.repository }} build
            cd build
            bash scripts/deploy.sh
