name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      APP_DIR: ${{ secrets.APP_DIR }}
      DATA_PATH: ${{ secrets.DATA_PATH }}
      GUILD_ID: ${{ secrets.GUILD_ID }}
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Deploy into production
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: APP_DIR,DATA_PATH,GUILD_ID,TOKEN
          script_path: scripts/deploy.sh

