name: Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "migrations/**"
      - "docker-compose.yml"
      - "Dockerfile"
      - "scripts/**"
      - "package*.json"
      - ".github/workflows/deploy.yml"

jobs:
  check_tagged:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      is_tagged: ${{ steps.check_tag.outputs.tagged }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Check if head is tagged
        id: check_tag
        run: |
          if [ -z "$(git tag --points-at HEAD)" ]; then
            echo "tagged=no" >> "$GITHUB_OUTPUT"
          else
            echo "tagged=yes" >> "$GITHUB_OUTPUT"
          fi

      - name: Update package version
        if: ${{ steps.check_tag.outputs.tagged == 'no' }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          current=$(jq -r .version package.json)
          base=$(echo "$current" | sed -E 's/-alpha\.[0-9]+$//')
          n=$(echo "$current" | grep -oP 'alpha\.\K[0-9]+' || echo 0)
          next_n=$((n + 1))
          next_version="$base-alpha.$next_n"
          jq --arg v "$next_version" '.version = $v' package.json > package.tmp.json
          mv package.tmp.json package.json
          git add package.json
          git commit -m "Update package version to $next_version"
          git tag $next_version
          git push --tags
          git push
  deploy:
    needs: check_tagged
    if: ${{ needs.check_tagged.outputs.is_tagged == 'yes' }}
    runs-on: ubuntu-latest
    environment: production
    env:
      APP_DIR: ${{ secrets.APP_DIR }}
      DATA_DIR: ${{ secrets.DATA_DIR }}
      BACKUP_DIR: ${{ secrets.BACKUP_DIR }}
      GUILD_ID: ${{ secrets.GUILD_ID }}
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Deploy into production
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: APP_DIR,DATA_DIR,GUILD_ID,TOKEN,BACKUP_DIR
          script: |
            cd $(mktemp -d)
            git clone https://github.com/${{ github.repository }} build
            cd build
            bash scripts/deploy.sh
